import os

base_dir = r"D:\Agente X"
directories = [
    "00_GOVERNANCE/RULES",
    "00_GOVERNANCE/WORKFLOWS",
    "00_GOVERNANCE/SKILLS",
    "00_GOVERNANCE/CONTAINERS",
    "01_CORE/orchestrator",
    "01_CORE/hierarchy_engine",
    "01_CORE/workflow_engine",
    "01_CORE/mission_engine",
    "01_CORE/rule_engine",
    "01_CORE/validation_engine",
    "02_MEMORY/short_term",
    "02_MEMORY/long_term",
    "02_MEMORY/vector_memory",
    "02_MEMORY/memory_index",
    "03_RUNTIME/logs",
    "03_RUNTIME/telemetry",
    "03_RUNTIME/sessions",
    "03_RUNTIME/evidence",
    "04_SKILLS/github",
    "04_SKILLS/obsidian",
    "04_SKILLS/research",
    "04_SKILLS/validation",
    "04_SKILLS/planning",
    "04_SKILLS/documentation",
    "05_WORKFLOWS/mission_execution",
    "05_WORKFLOWS/create_test_validate",
    "05_WORKFLOWS/governance",
    "05_WORKFLOWS/synchronization",
    "06_CONTAINERS/memory",
    "06_CONTAINERS/chat",
    "06_CONTAINERS/tools",
    "06_CONTAINERS/validation",
    "06_CONTAINERS/missions",
    "07_MISSIONS/pending",
    "07_MISSIONS/active",
    "07_MISSIONS/completed",
    "07_MISSIONS/failed",
    "08_AUDITS/forensic",
    "08_AUDITS/runtime",
    "08_AUDITS/truth_validation",
    "08_AUDITS/reports",
    "09_LOGS/system",
    "09_LOGS/runtime",
    "09_LOGS/governance",
    "09_LOGS/missions",
    "10_GITHUB/sync_reports",
    "10_GITHUB/commit_history",
    "11_OBSIDIAN/architecture",
    "11_OBSIDIAN/mission_reports",
    "11_OBSIDIAN/daily_notes",
    "11_OBSIDIAN/knowledge_base",
    "12_CONFIG/providers",
    "12_CONFIG/hierarchy",
    "12_CONFIG/governance",
    "12_CONFIG/environments",
    "13_BACKUPS_DIARIOS",
    "14_OBSIDIAN_EXPORT_DIARIO"
]

for d in directories:
    os.makedirs(os.path.join(base_dir, d), exist_ok=True)

print("Directories created successfully.")
